export const PUZZLE_STATUS = {
	NOT_STARTED: "NOT_STARTED",
	OBSERVED: "OBSERVED",
	UNLOCKED: "UNLOCKED",
	SOLVED: "SOLVED",
}

export const PUZZLE_KIND = {
	KEY_RIDDLE_BOUNTY: "KEY_RIDDLE_BOUNTY",
	BOUNTY: "BOUNTY",
}

export const PLAYER_ROLE = {
	LEADER: "LEADER",
	DETECTIVE: "DETECTIVE",
	NEGOTIATOR: "NEGOTIATOR",
	ARTIST: "ARTIST",
}

export const PLAYER_TEAM = {
	SHERLOCK: "SHERLOCK",
	MORIARTY: "MORIARTY",
	NEUTRAL: "NEUTRAL",
}

export const TRADE_STATUS = {
	TRADING: "TRADING",
	ACCEPTED: "ACCEPTED",
}
